version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--log.level=ERROR"
      - "--api.dashboard=true"
      #- "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=main-network"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - main-network
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: 
      web-adonis
    ports:
      - 8080:8080
    volumes:
      - ./web/:/home/node/app
      - web-node-modules:/home/node/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stellarium-web.rule=Host(`localhost`)"
      - "traefik.http.routers.stellarium-web.entrypoints=web"
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_NAME=stellarium
      - APP_URL=http://0.0.0.0:3333
      - CACHE_VIEWS=false
      - SESSION_DRIVER=cookie
    depends_on:
      - traefik
    restart: always
    networks: 
      - main-network
networks: 
  main-network:
    driver: bridge
volumes:
  web-node-modules: